using Microsoft.Extensions.Logging;
using Npgsql;

namespace TradingTerminal.Infrastructure.MarketData.Store;

/// <summary>
/// Creates the canonical schema in PostgreSQL and, when the TimescaleDB extension is present,
/// turns the high-volume tables into hypertables (time-partitioned for fast range scans and
/// ingest). Timestamps are native <c>TIMESTAMPTZ</c>. Idempotent — safe to run on every startup.
/// If the timescaledb extension isn't available the tables still work as plain Postgres.
/// </summary>
internal static class TimescaleSchema
{
    /// <summary>Maps <see cref="DateTime"/> of any kind to a UTC value Npgsql accepts for timestamptz.</summary>
    public static DateTime Utc(DateTime d) => d.Kind switch
    {
        DateTimeKind.Utc => d,
        DateTimeKind.Local => d.ToUniversalTime(),
        _ => DateTime.SpecifyKind(d, DateTimeKind.Utc),
    };

    /// <summary>Applies (or refreshes) retention policies on each hypertable per the options.
    /// Idempotent — safe to call after <see cref="EnsureCreated"/> on every startup.</summary>
    public static void ApplyRetention(
        NpgsqlConnection cn,
        int quoteDays, int tradeDays, int barDays,
        ILogger logger)
    {
        // Each call short-circuits when the hypertable doesn't exist (plain Postgres) or the
        // extension isn't present. add_retention_policy with if_not_exists is idempotent;
        // remove_retention_policy clears a previously-configured window when the user sets the
        // option back to 0 (= forever).
        Try(cn, "quotes",  quoteDays, logger);
        Try(cn, "trades",  tradeDays, logger);
        Try(cn, "bars",    barDays,   logger);
    }

    private static void Try(NpgsqlConnection cn, string table, int days, ILogger logger)
    {
        try
        {
            using var cmd = cn.CreateCommand();
            if (days > 0)
            {
                cmd.CommandText = $"SELECT add_retention_policy('{table}', INTERVAL '{days} days', if_not_exists => TRUE);";
                cmd.ExecuteNonQuery();
                logger.LogInformation("TimescaleDB retention: {Table} kept {Days} days", table, days);
            }
            else
            {
                cmd.CommandText = $"SELECT remove_retention_policy('{table}', if_exists => TRUE);";
                cmd.ExecuteNonQuery();
            }
        }
        catch (Exception ex)
        {
            logger.LogDebug(ex, "Retention policy skipped for {Table} (timescale extension missing or table not a hypertable)", table);
        }
    }

    public static void EnsureCreated(NpgsqlConnection cn, ILogger logger)
    {
        using (var cmd = cn.CreateCommand())
        {
            cmd.CommandText = """
                CREATE TABLE IF NOT EXISTS instruments (
                    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    canonical_symbol TEXT NOT NULL,
                    asset_class      INT  NOT NULL,
                    exchange         TEXT NOT NULL DEFAULT '',
                    currency         TEXT NOT NULL DEFAULT 'USD',
                    tick_size        DOUBLE PRECISION NOT NULL DEFAULT 0.01,
                    multiplier       DOUBLE PRECISION NOT NULL DEFAULT 1.0,
                    UNIQUE (canonical_symbol, asset_class, exchange)
                );

                CREATE TABLE IF NOT EXISTS instrument_aliases (
                    broker           INT  NOT NULL,
                    broker_symbol    TEXT NOT NULL,
                    broker_native_id TEXT,
                    instrument_id    INT  NOT NULL REFERENCES instruments(id),
                    PRIMARY KEY (broker, broker_symbol)
                );

                CREATE TABLE IF NOT EXISTS quotes (
                    instrument_id INT  NOT NULL,
                    event_time    TIMESTAMPTZ NOT NULL,
                    ingest_time   TIMESTAMPTZ NOT NULL,
                    bid           DOUBLE PRECISION NOT NULL,
                    ask           DOUBLE PRECISION NOT NULL,
                    bid_size      BIGINT NOT NULL,
                    ask_size      BIGINT NOT NULL,
                    source        INT NOT NULL,
                    seq           BIGINT NOT NULL,
                    approx_time   BOOLEAN NOT NULL
                );
                CREATE INDEX IF NOT EXISTS ix_quotes_instr_time ON quotes(instrument_id, event_time);

                CREATE TABLE IF NOT EXISTS trades (
                    instrument_id INT  NOT NULL,
                    event_time    TIMESTAMPTZ NOT NULL,
                    ingest_time   TIMESTAMPTZ NOT NULL,
                    price         DOUBLE PRECISION NOT NULL,
                    size          BIGINT NOT NULL,
                    aggressor     INT NOT NULL,
                    source        INT NOT NULL,
                    seq           BIGINT NOT NULL,
                    approx_time   BOOLEAN NOT NULL
                );
                CREATE INDEX IF NOT EXISTS ix_trades_instr_time ON trades(instrument_id, event_time);

                CREATE TABLE IF NOT EXISTS bars (
                    instrument_id INT NOT NULL,
                    bar_size      INT NOT NULL,
                    open_time     TIMESTAMPTZ NOT NULL,
                    open          DOUBLE PRECISION NOT NULL,
                    high          DOUBLE PRECISION NOT NULL,
                    low           DOUBLE PRECISION NOT NULL,
                    close         DOUBLE PRECISION NOT NULL,
                    volume        BIGINT NOT NULL,
                    source        INT NOT NULL,
                    is_final      BOOLEAN NOT NULL,
                    PRIMARY KEY (instrument_id, bar_size, open_time)
                );
                """;
            cmd.ExecuteNonQuery();
        }

        // Best-effort hypertable conversion. No-op on plain Postgres (extension absent).
        try
        {
            using var cmd = cn.CreateCommand();
            cmd.CommandText = """
                CREATE EXTENSION IF NOT EXISTS timescaledb;
                SELECT create_hypertable('quotes','event_time', if_not_exists => TRUE, migrate_data => TRUE);
                SELECT create_hypertable('trades','event_time', if_not_exists => TRUE, migrate_data => TRUE);
                SELECT create_hypertable('bars','open_time', if_not_exists => TRUE, migrate_data => TRUE);
                """;
            cmd.ExecuteNonQuery();
        }
        catch (Exception ex)
        {
            logger.LogInformation(ex, "TimescaleDB hypertables not created (plain Postgres?) — tables still usable.");
        }
    }
}
