<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TradingTerminal.Ai.Coordinator.Contracts\TradingTerminal.Ai.Coordinator.Contracts.csproj" />
  </ItemGroup>

</Project>
