using System.IO;
using System.Security.Cryptography;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TradingTerminal.Infrastructure.Plugins;

/// <summary>Whether a plugin folder matches the hashes the host pins for it.</summary>
public enum PluginPinResult
{
    /// <summary>No pinned hashes for this plugin — it's not one of ours. Fall through to the signature
    /// / consent path; NOT an error.</summary>
    NotPinned,

    /// <summary>Every assembly in the folder matches the pinned hash, and nothing was added or removed.
    /// This is a first-party plugin, exactly as it shipped.</summary>
    Match,

    /// <summary>The folder is pinned but its contents don't match — an assembly was modified, swapped,
    /// added, or removed. Something rewrote a shipped plugin.</summary>
    Tampered,
}

/// <summary>Sha256 of files, the one primitive the pin / integrity / revocation checks share.</summary>
public static class PluginIntegrity
{
    /// <summary>Uppercase hex sha256 of the file, or empty when it can't be read (a missing file is
    /// never silently "fine" — callers treat empty as a mismatch).</summary>
    public static string Sha256(string path)
    {
        try
        {
            using var stream = File.OpenRead(path);
            return Convert.ToHexString(SHA256.HashData(stream));
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or FileNotFoundException)
        {
            return string.Empty;
        }
    }
}

/// <summary>One pinned plugin: every assembly it shipped with, and that assembly's sha256.</summary>
public sealed record TrustedPlugin(
    [property: JsonPropertyName("plugin")] string Plugin,
    [property: JsonPropertyName("assemblies")] IReadOnlyDictionary<string, string> Assemblies);

/// <summary>
/// The host's pinned first-party plugin hashes (<c>plugins-trusted.json</c> in the plugins root,
/// generated by the build from the assemblies it actually staged).
/// <para>
/// This is how the shipped app trusts its OWN plugins without a code-signing certificate: rather than
/// requiring an Authenticode signature nobody has yet, the Curated policy accepts a plugin whose folder
/// hashes exactly to what the build produced. It doubles as the integrity check — if any shipped
/// assembly is modified, swapped, added, or deleted, the plugin no longer matches and is quarantined
/// as <see cref="PluginPinResult.Tampered"/> rather than silently loading rewritten code.
/// </para>
/// <para>
/// Third-party plugins are simply not listed (<see cref="PluginPinResult.NotPinned"/>) and go through
/// the signature / consent path instead.
/// </para>
/// </summary>
public sealed class PluginTrustedHashes
{
    public const string FileName = "plugins-trusted.json";

    private static readonly JsonSerializerOptions JsonOptions = new() { PropertyNameCaseInsensitive = true };

    private readonly Dictionary<string, IReadOnlyDictionary<string, string>> _pinned;

    private PluginTrustedHashes(Dictionary<string, IReadOnlyDictionary<string, string>> pinned) => _pinned = pinned;

    /// <summary>Empty set — nothing is pinned (a dev build with no generated manifest, or a bad file).
    /// Everything then falls through to the signature/consent path, which is the safe direction.</summary>
    public static PluginTrustedHashes Empty { get; } = new([]);

    public bool IsEmpty => _pinned.Count == 0;

    /// <summary>Reads <see cref="FileName"/> from the plugins root. A missing or corrupt file yields
    /// <see cref="Empty"/> — it must never take startup down; it just means nothing is pinned.</summary>
    public static PluginTrustedHashes Load(string pluginsRoot)
    {
        var path = Path.Combine(pluginsRoot, FileName);
        if (!File.Exists(path)) return Empty;

        try
        {
            var dto = JsonSerializer.Deserialize<TrustedDto>(File.ReadAllText(path), JsonOptions);
            if (dto?.Plugins is not { Count: > 0 }) return Empty;

            var pinned = new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase);
            foreach (var entry in dto.Plugins)
            {
                if (string.IsNullOrWhiteSpace(entry.Plugin) || entry.Assemblies is null) continue;
                pinned[entry.Plugin] = new Dictionary<string, string>(entry.Assemblies, StringComparer.OrdinalIgnoreCase);
            }
            return new PluginTrustedHashes(pinned);
        }
        catch (Exception ex) when (ex is JsonException or IOException or UnauthorizedAccessException)
        {
            return Empty;
        }
    }

    /// <summary>Compares the plugin folder on disk against the pinned hashes: every assembly present
    /// must be pinned with the same hash, and every pinned assembly must still be there. Anything else
    /// is tampering.</summary>
    public PluginPinResult Verify(string pluginFolderName, string pluginDirectory, out string? detail)
    {
        detail = null;
        if (!_pinned.TryGetValue(pluginFolderName, out var expected)) return PluginPinResult.NotPinned;

        var onDisk = Directory.Exists(pluginDirectory)
            ? Directory.EnumerateFiles(pluginDirectory, "*.dll").ToList()
            : [];

        foreach (var file in onDisk)
        {
            var name = Path.GetFileName(file);
            if (!expected.TryGetValue(name, out var expectedHash))
            {
                detail = $"'{name}' was added to a first-party plugin folder";
                return PluginPinResult.Tampered;
            }
            if (!string.Equals(PluginIntegrity.Sha256(file), expectedHash, StringComparison.OrdinalIgnoreCase))
            {
                detail = $"'{name}' does not match the assembly this build shipped";
                return PluginPinResult.Tampered;
            }
        }

        var present = onDisk.Select(Path.GetFileName).ToHashSet(StringComparer.OrdinalIgnoreCase);
        foreach (var missing in expected.Keys.Where(k => !present.Contains(k)))
        {
            detail = $"'{missing}' is missing from a first-party plugin folder";
            return PluginPinResult.Tampered;
        }

        return PluginPinResult.Match;
    }

    /// <summary>Compares one self-contained artifact against its pinned hash. Protected DAXQ packages
    /// may live directly in the plugins root, so their integrity check cannot enumerate the containing
    /// directory as the managed-folder check above does.</summary>
    public PluginPinResult VerifyArtifact(string pluginName, string artifactPath, out string? detail)
    {
        detail = null;
        if (!_pinned.TryGetValue(pluginName, out var expected)) return PluginPinResult.NotPinned;

        var fileName = Path.GetFileName(artifactPath);
        if (!expected.TryGetValue(fileName, out var expectedHash))
        {
            detail = $"'{fileName}' is not the protected artifact this build shipped";
            return PluginPinResult.Tampered;
        }

        if (expected.Count != 1)
        {
            detail = "the pinned protected-strategy package contains unexpected additional artifacts";
            return PluginPinResult.Tampered;
        }

        if (!string.Equals(PluginIntegrity.Sha256(artifactPath), expectedHash, StringComparison.OrdinalIgnoreCase))
        {
            detail = $"'{fileName}' does not match the protected artifact this build shipped";
            return PluginPinResult.Tampered;
        }

        return PluginPinResult.Match;
    }

    private sealed class TrustedDto
    {
        [JsonPropertyName("plugins")] public List<TrustedPlugin>? Plugins { get; set; }
    }
}
