using System.IO;
using System.Reflection;

namespace TradingTerminal.Infrastructure.Strategies.Authoring;

/// <summary>
/// The AI context pack (<c>sdk/ai-context/daxalgo-strategy-context.md</c>), embedded into this assembly
/// at build so it ships with the app and is the system prompt for the in-app AI builder. Generated by
/// <c>build/gen-ai-context.ps1</c> — read as a resource, never re-parsed.
/// </summary>
public sealed class StrategyContextPack
{
    internal const string ResourceName = "DaxAlgo.AiContext.StrategyPack.md";

    /// <summary>The pack text — the codegen system prompt.</summary>
    public string SystemPrompt { get; }

    private StrategyContextPack(string systemPrompt) => SystemPrompt = systemPrompt;

    /// <summary>Loads the embedded pack. Throws if the resource is missing (a build wiring error, not a
    /// runtime condition) so it surfaces in tests rather than as an empty prompt in production.</summary>
    public static StrategyContextPack Load()
    {
        var asm = typeof(StrategyContextPack).Assembly;
        using var stream = asm.GetManifestResourceStream(ResourceName)
            ?? throw new InvalidOperationException(
                $"AI context pack resource '{ResourceName}' is not embedded — check the EmbeddedResource in TradingTerminal.Infrastructure.csproj.");
        using var reader = new StreamReader(stream);
        return new StrategyContextPack(reader.ReadToEnd());
    }
}
